env:
- IP=128.199.134.167 PORT=80 DEPLOY_DIR=/usr/src/truegrail-frontend-web
addons:
  ssh_known_hosts: 128.199.134.167
cache: node_modules
branches:
  only:
  - master
language: node_js
node_js: 10.10.0
before_install:
- openssl aes-256-cbc -K $encrypted_066bf32c081b_key -iv $encrypted_066bf32c081b_iv -in id_rsa_travis_grail.enc -out id_rsa_travis_grail -d
- chmod u+x deploy.sh
after_success:
- sudo sh ./deploy/after_success.sh